### PR TITLE
Added image proxy extension

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks :+1:  This looks interesting.
It would be good to have the possibility of having the FreshRSS server do the proxying itself, without necessarily using a third-party service. If you can, please consider adding an option, or maybe simply a readme explaining the choice of the proxy service and possibility of self-hosting.

**Comment by Frenzie** [comment]
Good point. How about something like this?

**Comment by Frenzie** [comment]
Would you like me to change anything about the README.md?

**Comment by Alkarex** [comment]
Sorry, I had forgotten about this pull request...
Thanks!

**Pull request merged**
