### PR TITLE
xExtension-ShareByEmail: add german localization

### PR DESCRIPTION
**Pull request by Green-Kite**
add german localization

### CODE REVIEW

**Review by math-GH — APPROVED** [review]
didn't test, but the translation looks fine for me

**Comment by Alkarex** [comment]
You might have to bump the version number in
https://github.com/FreshRSS/Extensions/blob/master/xExtension-ShareByEmail/metadata.json

**Comment by jonastaedcke** [comment]
You use „Mail“ and „E-Mail“. I think it would be better to use only one of the two options in all cases.

**Comment by Frenzie** [comment]
Haha, indeed. I'd say go with "Mail," the "E-" part is a bit awkward and I don't think anybody says it anymore.

**Comment by Alkarex** [comment]
Can any of you finalize the PR accordingly?

**Comment by Frenzie** [comment]
I pushed a commit removing the "E-".

**Comment by Alkarex** [comment]
Could you also bump the version number?

**Pull request merged**
