### PR TITLE
Added Pocket Button extension

### PR DESCRIPTION
**Pull request by christian-putzke**
I've developed a small extension to be able to add articles to Pocket with a single button tap or a custom keyboard shortcut for myself.

Would be glad if you'll merge it and hope it will also be userful for others :)

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks! As a suggestion of improvement, you could avoid a jQuery dependency (risks of conflicts with other extensions, code size 4 times larger - the library being larger than your whole extension -, reduced performance, more HTTP requests, less standard, maintenance over time). The code is trivial to replace in native JavaScript (we removed jQuery from FreshRSS in 2018).

* https://youmightnotneedjquery.com/
* https://github.com/MachinisteWeb/vanilla-js-dom

Feel free to ask if there is any jQuery function for which you need help finding the native variant.

**Comment by christian-putzke** [comment]
Thanks for merging!
Great feedback regarding jQuery. I'll try to get rid of it during the next weeks.

**Comment by Alkarex** [comment]
P.S. Support for Internet Explorer 11 was dropped since [FreshRSS 1.19.0 ](https://github.com/FreshRSS/FreshRSS/releases/tag/1.19.0)

**Comment by christian-putzke** [comment]
Got some time today and removed the dependecy to jQuery. I filed a new pull request as I changed the `extensions.json` manually in this one but didn't realize one has to change `repositories.json` in order to let GitHub actions consider my repository.

**Comment by math-GH** [comment]
@christian-putzke : There is a simple Pocket sharing option already implemented in FreshRSS. Have you tried the sharing option "Pocket" too?

**Comment by christian-putzke** [comment]
I tried it but wasn't satisfied. It always opens a new tab which you need to manually close afterwards. You also have to stay logged in into Pocket. With the extension I can simply press a keyboard shortcut and everything else happens in the background while I can continue reading articles without any interruptions.

**Pull request merged**
