### PR TITLE
New extension: Comics in feed

### PR DESCRIPTION
**Pull request by giventofly**
Added Comics in feed extension.

### CODE REVIEW

**Review by Alkarex — CHANGES_REQUESTED** [review]
Hello,
https://github.com/FreshRSS/Extensions/blob/master/repositories.json needs to be also updated, and then run `make build`.
See an example from another PR such as https://github.com/FreshRSS/Extensions/pull/153/files

**Comment by giventofly** [comment]
Updated with the requested changes

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
I have combined your PRs for you.
To improve your extension, try to avoid making some changes at each refresh, but only for new entries, and also make sure to preserve their hash:

* https://github.com/FreshRSS/FreshRSS/issues/1706#issuecomment-348772243
    * Example https://github.com/kevinpapst/freshrss-dilbert/pull/1/files
* https://github.com/FreshRSS/FreshRSS/discussions/5602

**Comment by giventofly** [comment]
Thank you, will do

**Pull request merged**
