### PR TITLE
youtube extension can also display peertube videos

### PR DESCRIPTION
**Pull request by PhieF**
Updating description + youtube extension version

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks!

**Comment by kevinpapst** [comment]
@PhieF there is a bug now in the extension panel https://your-freshrss/i/?c=extension as it does not recognize the extension as being installed, due to the changed name.

@Frenzie the code wasn't merged in my repo^^ I wanted to rethink the merge of the two video sites first.

**Comment by Frenzie** [comment]
Whoops, my bad. I guess I didn't expect someone to open a PR like this without titling it WIP or some such if it wasn't yet merged. Should I revert it?

**Comment by kevinpapst** [comment]
Nah, now I was forced to merge it ;-)
We just should fix the issue with the extension not displaying an update. I will check if its only the title and sent in a new PR

**Pull request merged**
