### PR TITLE
Address phpstan ImageProxy complaints

### PR DESCRIPTION
**Pull request by Frenzie**
Re. https://github.com/FreshRSS/Extensions/pull/208#issuecomment-1971845385

### CODE REVIEW

**Comment by Alkarex** [comment]
Please run:

```sh
vendor/bin/phpstan analyse --level 9 .
```

or remove the lines from https://github.com/FreshRSS/Extensions/blob/master/tests/phpstan-next.txt and then run the full tests:

```sh
make test-all
```

**Comment by Alkarex** [comment]
```console
$ vendor/bin/phpstan analyse --level 9 .
Note: Using configuration file /home/alex/GitHub/Extensions/phpstan.neon.
 41/41 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------ 
  Line   xExtension-ImageProxy/configure.phtml                                                     
 ------ ------------------------------------------------------------------------------------------ 
  :10    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url.             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :16    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_http.     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :22    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_https.    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :29    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_default.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :29    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_default.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :40    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
  :46    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url_encode.      
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property      
 ------ ------------------------------------------------------------------------------------------ 

 ------ ---------------------------------------------------------------------------------------------------------- 
  Line   xExtension-ImageProxy/extension.php                                                                       
 ------ ---------------------------------------------------------------------------------------------------------- 
  :15    Strict comparison using === between FreshRSS_SystemConfiguration and null will always evaluate to false.  
  :24    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url.                             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :28    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_http.                     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :32    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_https.                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :35    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_force.                           
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :41    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_default.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :45    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :49    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url_encode.                      
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :62    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url.                             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :63    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_http.                     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :64    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_https.                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :65    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_default.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :66    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :67    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url_encode.                      
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :76    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_http.                     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :79    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :83    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_https.                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :86    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :90    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_default.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :91    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :95    Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_scheme_include.                  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :104   Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url_encode.                      
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
  :107   Access to an undefined property FreshRSS_UserConfiguration::$image_proxy_url.                             
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                      
 ------ ---------------------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 30 errors                                                                                                
                                                                                                                        
```

**Comment by Alkarex** [comment]
Explanations in https://github.com/FreshRSS/Extensions/issues/202

**Comment by Alkarex** [comment]
I had forgotten about https://github.com/FreshRSS/Extensions/pull/201
Merged, sorry for the mess :-)

**Comment by Alkarex** [comment]
> when I run `vendor/bin/phpstan analyse --level 9 .` it shows this. On all files.

To run the tests, PHPStan needs to have access to the FreshRSS repo as well, which is by convention at the same level than the `Extensions` folder:

https://github.com/FreshRSS/Extensions/blob/265fd0bb5c443915e6de00a7ff5e081ae26cca7f/phpstan.neon#L9

**Comment by Frenzie** [comment]
> I had forgotten about #201 Merged, sorry for the mess :-)

I did notice the wrong type was introduced in #185 but I figured that was just a typo.

I am still curious how to make phpstan not complain about all the classes it doesn't know though?

**Comment by Frenzie** [comment]
> > when I run `vendor/bin/phpstan analyse --level 9 .` it shows this. On all files.
> 
> To run the tests, PHPStan needs to have access to the FreshRSS repo as well, which is by convention at the same level than the `Extensions` folder:

Thanks, it would be useful if it complained that folder didn't exist or something. :-)

**Comment by Alkarex** [comment]
> it would be useful if it complained that folder didn't exist or something. :-)

Indeed, that would be a nice improvement, and can probably be done with a shell test

**Comment by Frenzie** [comment]
Actually, that changes nothing. It still says it can't find anything.

**Comment by Alkarex** [comment]
Do you have a structure with the two repos along side each other?
- ./FreshRSS/
- ./Extensions/

If so, maybe `rm -fr /tmp/phpstan/`

**Comment by Frenzie** [comment]
```
~/src/feeds$ ls
Extensions  FreshRSS
~/src/feeds$ cd Extensions/
~/src/feeds/Extensions$ vendor/bin/phpstan analyse --level 9 .
Note: Using configuration file /home/frans/src/feeds/Extensions/phpstan.neon.
 36/36 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------------------------------- 
  Line   xExtension-ColorfulList/extension.php                                
 ------ --------------------------------------------------------------------- 
  5      Class ColorfulListExtension extends unknown class Minz_Extension.    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  8      Call to an undefined method ColorfulListExtension::getFileUrl().     
  8      Call to static method appendScript() on an unknown class Minz_View.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
```

**Comment by Frenzie** [comment]
> If so, maybe `rm -fr /tmp/phpstan/`

Yes, that did the trick. Thanks!

**Pull request closed without merging**
