### PR TITLE
Suppression de l'extension Hooktube

### PR DESCRIPTION
**Pull request by Korbak**
Hooktube étant un site tenu par un néo-nazi, l'extension Hooktube le soutenait, ce que je refuse. De ce fait, j'ai supprimé mon extension, et la supprime donc de la liste.

### CODE REVIEW

**Comment by Frenzie** [comment]
@Korbak That's too bad. :-(

@Alkarex I don't really understand what's going on here. Although I see the removal in the commits, GitHub's "files changed" only shows an added newline or something?

**Comment by kevinpapst** [comment]
I guess that is happening because the 3 first commits were already merged, what honestly doesn't make a lot of sense. 
@Korbak can you rebase your branch onto the current master?

**Comment by Alkarex** [comment]
@Korbak Please send another PR based on the current, up-to-date /master branch.

**Comment by Korbak** [comment]
Sorry for the answering time, I can see that you guys already did what was needed.
Also, pardon my french on the PR. I copy-pasted things from my own github to Freshrss's one.
Hope I will have other opportunities to contribute.
Thanks for everything.
<3.

**Pull request merged**
