### PR TITLE
Add PHPStan and other quality checks

### PR DESCRIPTION
**Pull request by Alkarex**
Similar to FreshRSS core
Contributes to https://github.com/FreshRSS/Extensions/issues/184
Uses https://github.com/FreshRSS/FreshRSS/pull/5901

TODO:

* [x] Check compatibility with PHP 7.4 - PHP 8.3

### CODE REVIEW

**Comment by Alkarex** [comment]
Only lacking a bit of work on:
* `./xExtension-ImageProxy/configure.phtml`
* `./xExtension-ImageProxy/extension.php`

Any takers please 🙏🏻?
Maybe @Frenzie or @ColonelMoutarde?

This PR can be also merged as-is after a bit of testing.
Anyone to give it a try? @lapineige or @math-GH maybe?

**Comment by Alkarex** [comment]
I thought there was an issue (maybe by @math-GH ) somewhere about doing this PR, but I cannot find it at the moment... (Hints welcome)

**Comment by lapineige** [comment]
I've no time to test it, sorry.

**Comment by Frenzie** [comment]
@Alkarex Probably not for a week, slightly depending on the weather.

**Comment by math-GH** [comment]
Sorry, I am late to the party.
In my first check I saw an PHP error with 1.22.2-dev about 10 commits behind. I mean: Does this PR works fine with the current 1.22.1? The users have 1.22.1 installed and add extensions from the repository. Sure that the current extensions (that includes this PR) work fine?

**Comment by Alkarex** [comment]
No, there is no possible path of update without also making a new FreshRSS release, so we need to issue [1.23.0](https://github.com/FreshRSS/FreshRSS/milestones/1.23.0) as soon as possible.
It also indicates the need to have some version ranges for compatibility in the metadata.
Help very much wanted in finalising the work on the extension updates (tests in particular, before the release of 1.23.0)

`xExtension-ImageProxy` is also in need of a caring hand (maybe @ColonelMoutarde while @Frenzie is away)

**Comment by Alkarex** [comment]
What lacks most urgently is testing the compatibility with older third-party extensions, which have _not_ been updated

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/pull/5837

**Pull request merged**
